### ISSUE TITLE
Incorrect label for plots that haven't been placard examined this phase

### ISSUE THREAD

**Issue by manyinsects** [zhudotexe/zhu.codes#4]
Some worlds have lots of plot entries that show "outdated data" despite last being updated minutes ago, well into the current lotto phase. This, I think, is because internally, it still has a lotto phase associated with it, but it's only been scouted via the residential aethernet overview this lotto phase, meaning that, if anything, it should be listed as "missing data", or maybe even a third, distinct thing.

This is probably the code that would need to be changed. I can send a pull request once there's a consensus on what the behavior should be :) https://github.com/zhudotexe/zhu.codes/blob/master/src/views/paissa/utils.ts#L46

**Comment by zhudotexe** [comment]
I think you're right - "Missing Data" or ~~"Missing Lotto Count"~~ "Missing Placard Data" both work imo. Thanks!
