### ISSUE TITLE
Purge Outdated/Missing Data periodically

### ISSUE THREAD

**Issue by ZohiDev** [zhudotexe/zhu.codes#6]
I may be misunderstanding the purpose, but currently the results of PaissaDB are insanely inaccurate due to the large number of plots with "Outdated Data" or "Missing Data" Status'.

Can these entries be periodically purged? Since the plugin is scanning each Ward and updating the db/website, you'd be able to discern that "ward 1 plot 1 has a house on it now. clearly it is not "missing data" any longer" and update the listing

**Comment by zhudotexe** [comment]
The plugin already does this. Can you give an example of some currently inaccurate plots to aid with debugging? (I currently do not have an active FFXIV sub)

**Comment by zhudotexe** [comment]
I double-checked with a friend and it appears that the "outdated" plots are still accurate. I've updated the way PaissaDB updates this field so it should more accurately reflect that the plot is still available (previously, it only updated the last updated field when it received a placard update; now it updates the field from aetheryte updates too if it has not yet received a placard update).

If you can find some examples of inaccurate plots, please let me know.
